MyProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^search',include('search.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('library.urls')),
    url(r'^admin/', admin.site.urls),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    url(r'^register/$', views.RegisterFormView.as_view(),{'next_page' :'library:index'},name='register'),
    url(r'^login/$',auth_views.login,{'redirect_authenticated_user' :'library:index'},name='login',),
    url(r'^logout/$',auth_views.logout,{'next_page' :'library:index'},name='logout'),
]

library/urls.py
from django.conf.urls import url

from . import views

app_name = 'library'
urlpatterns = [
    url(r'^$', views.Home, name='index'),
]

#Book
urlpatterns += [
    url(r'^books/$',views.BookListView.as_view(),name='books'),
    url(r'^book/(?P<pk>[0-9]+)$', views.BookDetailView.as_view(), name='book'),
    url(r'^book/add/$', views.BookCreate.as_view(), name='book_add'),
    url(r'^book/(?P<pk>[0-9]+)/edit/$', views.BookUpdate.as_view(), name='book_edit'),
    url(r'^book/(?P<pk>[0-9]+)/delete/$', views.BookDelete.as_view(), name='book_del'),
]

#Author
urlpatterns += [
    url(r'^authors/$',views.AuthorListView.as_view(),name='authors'),
    url(r'^author/(?P<pk>[0-9]+)$', views.AuthorDetailView.as_view(), name='author'),
    url(r'^author/add/$', views.AuthorCreate.as_view(), name='author_add'),
    url(r'^author/(?P<pk>[0-9]+)/edit/$',views.AuthorUpdate.as_view(), name='author_edit'),
    url(r'^author/(?P<pk>[0-9]+)/delete/$', views.AuthorDelete.as_view(), name='author_del'),
]

search/urls.py
from django.conf.urls import url

from . import views


app_name = 'search'

urlpatterns = [
    url(r'^',views.search,name='search'),
]

accounts/models.py
from django.db import models

# Create your models here.

library/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Author(models.Model):
    name = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('library:author',
                       args=[str(self.id)])

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author,
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True)

    def get_absolute_url(self):
        return reverse('library:book',
                       args=[str(self.id)])

    def __str__(self):
        return self.title

search/models.py
from django.db import models

# Create your models here.

library/forms.py
from django import forms
from .models import  Book,Author


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author')


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('name',)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import FormView


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = '/accounts/login'
    template_name = 'registration/register.html'
    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

library/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.http import require_GET
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Book,Author


@require_GET
def Home(request):
    template = 'index.html'
    cnt_authors = Author.objects.all().count()
    cnt_books = Book.objects.all().count()
    context = {
        'cnt_books': cnt_books,
        'cnt_authors': cnt_authors
    }
    return render (request,template,context)


#book
class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'library/book.html'


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    template_name = 'library/book_new.html'


class BookUpdate(LoginRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    template_name = 'library/book_edit.html'


class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('library:books')
    template_name = 'library/book_del.html'


#author
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'library/author.html'


class AuthorCreate(LoginRequiredMixin,CreateView):
    model = Author
    fields = '__all__'
    template_name = 'library/author_new.html'


class AuthorUpdate(LoginRequiredMixin, UpdateView):
    model = Author
    fields = '__all__'
    template_name = 'library/author_edit.html'



class AuthorDelete(LoginRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('library:authors')
    template_name = 'library/author_del.html'

search/views.py
from django.db.models import Q
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from library.models import Book


def search(request):
    template = 'search/search.html'
    query = request.GET.get('q')
    if query:
        books = Book.objects.filter(Q(title__icontains=query) |
                                    Q(author__name__icontains=query))
        return render(request, template, {'books': books})
    return render(request, template, {'books':None})

library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Local Library{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url 'library:index' %}" class="navbar-brand">Library</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'library:books' %}">All books</a></li>
        <li><a href="{% url 'library:authors' %}">All authors</a></li>
        <li> <form class="navbar-search pull-right" action="{% url 'search:search' %}">
  				<input type="search" class="search-query" placeholder="Search" name="q" value="{{ request.GET.q }}">
  				<button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
    		</form><
    	</li>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        {% if user.is_authenticated %}
            <li><a href="#"><span class="glyphicon glyphicon-user"></span>{{ user.get_username }}</a></li>
            <li><a href="{% url 'accounts:logout'%}?next={{request.path}}">
                <span class="glyphicon glyphicon-user"></span> Logout</a>
            </li>
        {% else %}

            <li><a href="{% url 'accounts:login'%}?next={{request.path}}">
                <span class="glyphicon glyphicon-log-in"></span> Log in</a>
            </li>

        {% endif %}
      </ul>
    </div>

  </div>

</nav>

<div class="container">
  {% block content %}{% endblock %}
  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}

</div>

</body>
</html>

library/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>The library has:</h1>
        <ul>
            <li><h3>Books: {{ cnt_books }}</h3></li>
            <li><h3>Authors: {{ cnt_authors }}</h3></li>
        </ul>
{% endblock %}

library/templates/library/author.html
{% extends 'base.html' %}
{% block title %}
{{ author.name }}
{% endblock %}
{% block content %}
    <h1><small>Name: </small>{{ author.name }}</h1>
    <a class="btn btn-warning" href="{% url 'library:author_edit' author.id %}">Edit</a>
    <a  class="btn btn-danger" href="{% url 'library:author_del' author.id %}">Delete</a>
{% endblock %}

library/templates/library/author_del.html
{% extends 'base.html' %}
{% block title %}
{{ author.name }}
{% endblock %}
{% block content %}
<form class="form-horizontal" method="post" action="{% url 'library:author_del' author.id %}">
    {% csrf_token %}
        <h2>Are you sure delete {{ author.name }}?</h2>
    <div class="form-actions">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a  href="{%  url 'library:author' author.id %}" class="button cancel-link">No, take me back</a>
    </div>
</form>
{% endblock %}

library/templates/library/author_edit.html
{% extends "base.html" %}
{% block title %}
{{ author.name }}
{% endblock %}
{% block content %}
<form class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
            <div class="control-group
                {% if field.errors %} has-error {% endif %}">
                <label class="control-label">{{ field.label }}</label>
                <div class="controls">{{ field }}</div>
            </div>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>
{% endblock %}

library/templates/library/author_list.html
{% extends "base.html" %}
{% block title %}
Authors
{% endblock %}
{% block content %}
<h1>Author List:</h1>
<a class="btn btn-default" href="{% url 'library:author_add' %}">Add New Author</a>
{% if author_list %}
  <ul class="list-group">
  {% for author in author_list %}
    <li class="list-group-item"><h3><a href="{{ author.get_absolute_url }}">{{ author }} </a></h3></li>
  {% endfor %}
  </ul>
{% else %}
  <h3>There are no authors available.</h3>
{% endif %}
{% endblock %}

library/templates/library/author_new.html
{% extends "base.html" %}
{% block title %}
New Author
{% endblock %}
{% block content %}
{% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
{% endfor %}
<form class="form-horizontal" method="post" action="{% url 'library:author_add' %}">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
            <div class="control-group
                {% if field.errors %} has-error {% endif %}">
                <label class="control-label">{{ field.label }}</label>
                <div class="controls">{{ field }}</div>
            </div>
        {% endfor %}
    </fieldset>

    <div class="form-actions">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>
{% endblock %}

library/templates/library/book.html
{% extends 'base.html' %}
{% block title %}
{{ book.title }}
{% endblock %}
{% block content %}
    <h1> <small>Title: </small> {{ book.title }}</h1>
    {% if  book.author%}
        <h2> <small>Author: </small><a href="{% url 'library:author' book.author.id %}">{{ book.author }}</a></h2>
    {% else %}
        <h2>Author missing</h2>

    {% endif %}

    <a class="btn btn-warning" href="{% url 'library:book_edit' book.id %}">Edit</a>
    <a class="btn btn-danger" href="{% url 'library:book_del' book.id %}">Delete</a>
{% endblock %}

library/templates/library/book_del.html
{% extends 'base.html' %}
{% block title %}
{{ book.title }}
{% endblock %}
{% block content %}
<form class="form-horizontal" method="post" action="{% url 'library:book_del' book.id %}">
    {% csrf_token %}
        <h2>Are you sure delete {{ book.title }}?</h2>
    <div class="form-actions">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a href="{% url 'library:book' book.id %}" class="button cancel-link">No, take me back</a>
    </div>
</form>
{% endblock %}

library/templates/library/book_edit.html
{% extends 'base.html' %}
{% block title %}
{{ book.title }}
{% endblock %}
{% block content %}
{% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
{% endfor %}
<form class="form-horizontal" method="post" action="{% url 'library:book_edit' form.instance.id  %}">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
            <div class="control-group
                {% if field.errors %} has-error {% endif %}">
                <label class="control-label">{{ field.label }}</label>
                <div class="controls">{{ field }}</div>
            </div>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>
{% endblock %}

library/templates/library/book_list.html
{% extends "base.html" %}
{% block title %}
Books
{% endblock %}
{% block content %}
    <h1>Book List:</h1>
        <a class="btn btn-default" href="{% url 'library:book_add' %}">Add New Book</a>

    {% if book_list %}
    <ul class="list-group">
      {% for book in book_list %}
      <li class="list-group-item">
        <h3><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})</h3>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

library/templates/library/book_new.html
{% extends 'base.html' %}
{% block title %}
New Book
{% endblock %}
{% block content %}
{% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
{% endfor %}
<form class="form-horizontal" method="post" action="{% url 'library:book_add' %}">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
            <div class="control-group
                {% if field.errors %} has-error {% endif %}">
                <label class="control-label">{{ field.label }}</label>
                <div class="controls">{{ field }}</div>
            </div>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>
{% endblock %}

search/templates/search/search.html
{% extends 'base.html' %}
{% block content %}
    <h4> <small> {{ books.count }} results</small></h4>
    {% if books %}
        <ul>
        {% for book in books %}
            <li><h3> <a href="{% url 'library:book' book.id %}">{{ book.title }}</a>
            ({{ book.author }})
            </h3></li>
        {% endfor %}
        </ul>
    {% else %}
        <h3>Searching did't give results.</h3>
    {% endif %}
{% endblock %}